# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90e7e964ba0ad1b2d059bc284f388ecb524e3b80ac7ba1ed9be72c72edf03974c7bdaed3a1751041d1f64f7937b2692cfa8490daae4f939c367683f94d9ea70

test:
  secret_key_base: 8e74eddaba5e76e26fd052bca37cd61dd1f30db8f47098d7b8f306d8b9a0287dcb82bc03f909bd40932af37062152bf5cd3bccc38c98a1e1678d4cb62899be3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
